### ISSUE TITLE
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-idea-enhancer#1]
Information:Using javac 1.8.0_45 to compile java sources
Information:Ebean enhancement started ...
Information:com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
Indexing started at: java.lang.Throwable
at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:160)
at com.intellij.openapi.project.DumbServiceImpl.queueTask(DumbServiceImpl.java:85)
at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.doSynchronizeRoots(ProjectRootManagerComponent.java:298)
at com.intellij.openapi.roots.impl.ProjectRootManagerComponent$AppListener.writeActionFinished(ProjectRootManagerComponent.java:330)
at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
at com.sun.proxy.$Proxy5.writeActionFinished(Unknown Source)
at com.intellij.openapi.application.impl.ApplicationImpl.f(ApplicationImpl.java:1416)
at com.intellij.openapi.application.impl.ApplicationImpl.c(ApplicationImpl.java:1262)
at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1005)
at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl$1.run(RefreshSessionImpl.java:193)
at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:206)
at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl$1$1.run(RefreshQueueImpl.java:91)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:702)
at java.awt.EventQueue$3.run(EventQueue.java:696)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
## at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Information:  at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:871)
Information:  at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:818)
Information:  at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:801)
Information:  at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:242)
Information:  at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:223)
Information:  at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
Information:  at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
Information:  at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
Information:  at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.a(JavaFileManagerImpl.java:122)
Information:  at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:115)
Information:  at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
Information:  at com.intellij.psi.impl.JavaPsiFacadeImpl.a(JavaPsiFacadeImpl.java:124)
Information:  at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:101)
Information:  at org.avaje.idea.ebean.plugin.IdeaClassBytesReader.lookupClassBytesFallback(IdeaClassBytesReader.java:75)
Information:  at org.avaje.idea.ebean.plugin.IdeaClassBytesReader.getClassBytes(IdeaClassBytesReader.java:66)
Information:  at com.avaje.ebean.enhance.agent.EnhanceContext.getClassBytes(EnhanceContext.java:64)
Information:  at com.avaje.ebean.enhance.agent.ClassMetaReader.readFromResource(ClassMetaReader.java:54)
Information:  at com.avaje.ebean.enhance.agent.ClassMetaReader.getWithCache(ClassMetaReader.java:35)
Information:  at com.avaje.ebean.enhance.agent.ClassMetaReader.getWithCache(ClassMetaReader.java:38)
Information:  at com.avaje.ebean.enhance.agent.ClassMetaReader.get(ClassMetaReader.java:27)
Information:  at com.avaje.ebean.enhance.agent.EnhanceContext.getSuperMeta(EnhanceContext.java:118)
Information:  at com.avaje.ebean.enhance.agent.ClassAdapterEntity.visit(ClassAdapterEntity.java:84)
Information:  at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:622)
Information:  at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:506)
Information:  at com.avaje.ebean.enhance.agent.Transformer.entityEnhancement(Transformer.java:166)
Information:  at com.avaje.ebean.enhance.agent.Transformer.transform(Transformer.java:124)
Information:  at com.avaje.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:55)
Information:  at com.avaje.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:39)
Information:  at org.avaje.idea.ebean.plugin.EbeanEnhancementTask.doProcess(EbeanEnhancementTask.java:101)
Information:  at org.avaje.idea.ebean.plugin.EbeanEnhancementTask.access$000(EbeanEnhancementTask.java:45)
Information:  at org.avaje.idea.ebean.plugin.EbeanEnhancementTask$1.run(EbeanEnhancementTask.java:62)
Information:  at com.intellij.util.ActionRunner$1.run(ActionRunner.java:31)
Information:  at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
Information:  at com.intellij.openapi.application.WriteAction$1$1.run(WriteAction.java:48)
Information:  at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
Information:  at com.intellij.openapi.application.WriteAction$1.run(WriteAction.java:45)
Information:  at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:716)
Information:  at com.intellij.openapi.application.WriteAction.execute(WriteAction.java:42)
Information:  at com.intellij.util.ActionRunner.runInsideWriteAction(ActionRunner.java:33)
Information:  at org.avaje.idea.ebean.plugin.EbeanEnhancementTask.process(EbeanEnhancementTask.java:58)
Information:  at org.avaje.idea.ebean.plugin.CompiledFileCollector.compilationFinished(CompiledFileCollector.java:93)
Information:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Information:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Information:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Information:  at java.lang.reflect.Method.invoke(Method.java:497)
Information:  at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
Information:  at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:368)
Information:  at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:355)
Information:  at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:341)
Information:  at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:334)
Information:  at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
Information:  at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:223)
Information:  at com.sun.proxy.$Proxy70.compilationFinished(Unknown Source)
Information:  at com.intellij.compiler.CompilerManagerImpl$ListenerNotificator.finished(CompilerManagerImpl.java:485)
Information:  at com.intellij.compiler.impl.CompileDriver$5.run(CompileDriver.java:524)
Information:  at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
Information:  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
Information:  at java.awt.EventQueue.access$500(EventQueue.java:97)
Information:  at java.awt.EventQueue$3.run(EventQueue.java:702)
Information:  at java.awt.EventQueue$3.run(EventQueue.java:696)
Information:  at java.security.AccessController.doPrivileged(Native Method)
Information:  at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
Information:  at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
Information:  at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
Information:  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
Information:  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
Information:  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
Information:  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
Information:  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
Information:  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
Information:  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
Information:  at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Information:  at com.avaje.ebean.enhance.agent.EnhanceContext.getInterfaceMeta(EnhanceContext.java:137)
Information:  at com.avaje.ebean.enhance.agent.ClassAdapterDetectEnhancement.visit(ClassAdapterDetectEnhancement.java:108)
Information:  at com.avaje.ebean.enhance.agent.Transformer.detect(Transformer.java:254)
Information:  at com.avaje.ebean.enhance.agent.Transformer.transform(Transformer.java:108)

**Comment by rbygrave** [comment]
Seeing this issue when the plugin is invoked immediately after a mvn clean.

The issue is that the agent is looking to read MappedSuperclass classes, and when these are outside the set of compiled classes then it tries to read these via IntelliJ virtual class path ... and there is a timing issue where this is not ready.

The fix/workaround is to handle this exception as most generally the classes this errors on are not actually MappedSuperclass classes (hence have no interesting properties to read) and can be safely ignored with a warning.
