### ISSUE TITLE
Update to agent 10.2.1 using ebean.mf with entity-packages, transactional-packages and querybean-packages

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-idea-enhancer#16]

**Comment by perses-games** [comment]
After updating the idea plugin my war didn't deploy anymore and gives the following exception:

```
Caused by: java.lang.annotation.AnnotationFormatError: Duplicate annotation for class: interface io.ebean.typequery.AlreadyEnhancedMarker: @io.ebean.typequery.AlreadyEnhancedMarker()
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:125)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at io.ebeaninternal.server.core.bootup.BootupClasses.has(BootupClasses.java:474)
	at io.ebeaninternal.server.core.bootup.BootupClasses.isEmbeddable(BootupClasses.java:470)
	at io.ebeaninternal.server.core.bootup.BootupClasses.isMatch(BootupClasses.java:349)
	at org.avaje.classpath.scanner.internal.scanner.classpath.ClassPathScanner.scanForClasses(ClassPathScanner.java:111)
	at org.avaje.classpath.scanner.Scanner.scanForClasses(Scanner.java:86)
	at org.avaje.classpath.scanner.Scanner.scanForClasses(Scanner.java:98)
	at io.ebeaninternal.server.core.bootup.BootupClassPathSearch.getBootupClasses(BootupClassPathSearch.java:55)
	at io.ebeaninternal.server.core.bootup.BootupClassPathSearch.search(BootupClassPathSearch.java:31)
	at io.ebeaninternal.server.core.DefaultContainer.getBootupClasses1(DefaultContainer.java:227)
	at io.ebeaninternal.server.core.DefaultContainer.getBootupClasses(DefaultContainer.java:200)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:97)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:77)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:44)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:55)
	at io.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:201)
	at io.ebean.Ebean$ServerManager.<init>(Ebean.java:159)
	... 108 more
```

Changing the ebean.mf and ebean-typequery.mf files to use the entity-packages, transactional-packages and querybean-packages directives fixed this problem. But it would have been nice if the old way continued to work (perhaps with a warning). Or if that wasn't possible then a big warning in the release notes would have saved me a lot of trouble.

**Comment by rbygrave** [comment]
Are you sure?  This looks like a different problem (not related to package filtering).  

Are you able to reproduce the problem? (by reverting that change back to use ebean-typequery.mf)

**Comment by perses-games** [comment]
Yes, I tried to revert it and the problem returned. But maybe this is caused by something else?

Btw, building with the maven plugin kept working and I assume that it triggers the same code, so I don't know.
